In [1]:
import qcportal as ptl

client =ptl.FractalClient()

In [3]:
client

butane = client.query_molecules(id=['61139','70659'])
butane[0].show()
butane[1].show()
butane[0].atomic_numbers
butane[0].geometry
butane[0].symbols
butane_geometries=[butane[0].geometry.copy(),butane[1].geometry.copy()]

In [4]:
butane[0].show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [5]:
butane[1].show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [6]:
import numpy as np

def calculate_distance(rA, rB):
    """Calculate the distance between points A and B"""
    dist_vec = (rA - rB)
    distance = np.linalg.norm(dist_vec)
    return distance

In [7]:
atom1=butane_geometries[0][0]
print(atom1)


[ 0.60309252 -2.0666753  -2.95631542]


In [8]:
atom2=butane_geometries[0][1]
print(atom2)


[-0.54975128  2.07257294  2.96267825]


In [9]:
measured_distance=calculate_distance(atom1,atom2)
print(measured_distance)

7.314158248564329


In [10]:
butane[0].measure([0,1])

7.31415824856433

In [11]:
atom1=butane_geometries[1][2]
print(atom1)

[ 1.67240752 -1.04497304 -0.64735584]


In [12]:
atom2=butane_geometries[1][9]
print(atom2)

[-1.57944138  3.83705924  2.62381983]


In [13]:
measured_distance=calculate_distance(atom1,atom2)
print(measured_distance)

6.71634950813261


In [14]:
def build_bond_list(coordinates, max_bond=2.93, min_bond=0):
    num_atoms = len(coordinates)
    
    bonds = {}
    
    for atom1 in range(num_atoms):
        for atom2 in range(atom1, num_atoms):
            distance = calculate_distance(coordinates[atom1], coordinates[atom2])
            
            if distance > min_bond and distance < max_bond:
                bonds[(atom1, atom2)] = distance
    
    return bonds

In [15]:
bond_list=build_bond_list(butane_geometries[0],max_bond=2.93)
bond_list

{(0, 2): 2.873020656801253,
 (0, 4): 2.068839651551603,
 (0, 5): 2.068484041315794,
 (0, 6): 2.068821759435787,
 (1, 3): 2.873059651780396,
 (1, 7): 2.068247482474781,
 (1, 8): 2.0685780442929644,
 (1, 9): 2.0687346633381822,
 (2, 3): 2.8862132661474598,
 (2, 10): 2.0715801221019885,
 (2, 11): 2.0716218178677623,
 (3, 12): 2.0713472807014583,
 (3, 13): 2.071754810836534}

In [18]:
butane[0].connectivity

[(0, 2, 1.0),
 (0, 4, 1.0),
 (0, 5, 1.0),
 (0, 6, 1.0),
 (1, 3, 1.0),
 (1, 7, 1.0),
 (1, 8, 1.0),
 (1, 9, 1.0),
 (2, 3, 1.0),
 (2, 10, 1.0),
 (2, 11, 1.0),
 (3, 12, 1.0),
 (3, 13, 1.0)]

In [19]:
import qcelemental

In [23]:
#Use qcportal to access a geometry optimization calculation
#use query procedures
#id=2658710

calculation = client.query_procedures(id=2658710)
opt=calculation[0]



In [24]:
initial=opt.get_initial_molecule()
initial.show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [25]:
final=opt.get_final_molecule()
final.show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [26]:
initial.connectivity

In [27]:
#max bond length is 2.93
initial_coordinates=initial.geometry.copy()
final_coordinates=final.geometry.copy()

initial_bonds=build_bond_list(initial_coordinates,max_bond=2.93)
final_bonds=build_bond_list(final_coordinates,max_bond=2.93)

In [28]:
initial_bonds

{(0, 1): 2.6853008199999997,
 (0, 5): 2.685300947458371,
 (0, 54): 2.0494834766860643,
 (1, 6): 2.6853009524690883,
 (1, 55): 2.0494834766860643,
 (2, 3): 2.6853008199999997,
 (2, 9): 2.685300947458371,
 (2, 56): 2.0494834766860643,
 (3, 10): 2.6853009524690883,
 (3, 57): 2.0494834766860643,
 (4, 5): 2.685300829999999,
 (4, 13): 2.685300829993184,
 (4, 58): 2.0494834770587396,
 (5, 14): 2.6852998829666923,
 (6, 7): 2.68530082,
 (6, 15): 2.6852998879774117,
 (7, 16): 2.6852998879774117,
 (7, 59): 2.0494834871062877,
 (8, 9): 2.685300829999999,
 (8, 19): 2.685300829993184,
 (8, 60): 2.0494834770587396,
 (9, 20): 2.6852998829666923,
 (10, 11): 2.68530082,
 (10, 21): 2.6852998879774117,
 (11, 22): 2.6852998879774117,
 (11, 61): 2.0494834871062877,
 (12, 13): 2.685300829999999,
 (12, 24): 2.6852998829666923,
 (12, 62): 2.049483475383679,
 (13, 25): 2.685300829993184,
 (14, 15): 2.6853008199999997,
 (14, 26): 2.6852998829666923,
 (15, 27): 2.6852998879774117,
 (16, 17): 2.68530082,
 (16, 28)